project_id = "lsvqgofxdekozdupvchu"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[functions.ai-project-generator]
verify_jwt = false

[functions.ai-code-assistant]
verify_jwt = false

[functions.github-integration]
verify_jwt = false

[edge_runtime]
ip_version = "ipv4"