// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lsvqgofxdekozdupvchu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzdnFnb2Z4ZGVrb3pkdXB2Y2h1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNzQ2MTcsImV4cCI6MjA3MDY1MDYxN30.Tx5_Wj2Hc29yyNw6-qOteUZZkwiwKAm2A7B05UE7Jv8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});